services:
  - type: web
    name: n8n
    env: node
    plan: free
    buildCommand: yarn build
    startCommand: yarn start
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: 'true'
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: nakul_776
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: NODE_ENV
        value: production
